### ISSUE TITLE
FileMaker Pro Download Recipe

### ISSUE THREAD

**Issue by apizz** [autopkg/nzmacgeek-recipes#4]
Was trying to create overrides of your FileMaker Pro download receipt for version 16, and it appears the updaters for this version are now in ZIP files, which is causing the `hdiutil` command to fail.

I'm very much a Python novice and while the updaters are helpful, I'm also interested in getting the full installers for a given FileMaker Pro version, rather than just the incremental updater.

The full installers are at `http://fmdl.filemaker.com/maint/107-85rel/` and the file name is in the format of `fmp_<major_version>.X.X.XXX.dmg`.

**Comment by nzmacgeek** [comment]
Sounds fair enough. As we use FMP at our site, I'm going to have to fix this for our site too. If I can complete my understanding here:
- Updaters appear to be in zip files now.
- Full installers are also available, but it is not straightforward to find out the version of the latest release. My only thought here is to extract the version of latest _updater_ and see if this can be applied to get the latest full installer. It seems to appear to work with just banging that URL in Safari.

**Comment by apizz** [comment]
Your understanding is spot on.  My experience has been yours as well, manually entering the version number in the URL gets me the full installer, which can be collected from the updates page.

I agree that splitting the recipes would be best.  

Thank you!

**Comment by nzmacgeek** [comment]
Ugh, I may have pushed some code this morning in commit (c44835712c6c220a1701c5ffe2d29e09a1e8d2d6) that would have fixed it. Give it a try and let us know (my apologies, I completely bypassed good practice this morning!)

**Comment by apizz** [comment]
Confirmed that this recipe now downloads the full installer.  Thanks so much!

One thing - the updated FileMaker.download.recipe still has the old description of what the recipe does.

**Comment by nzmacgeek** [comment]
Indeed. I have fixed that now. Thanks for your help!
